apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    tier: frontend
    app: node-app
  externalTrafficPolicy: Cluster
  ports:
    - name: myport
      port: 8037
      protocol: TCP
      targetPort: 3040
  type: LoadBalancer
